# environment
task: "Pendulum-v1"
exp_name: td_mpc_no_latent_ctr
save_path: "models/${task}/${exp_name}_${seed}.pt"
modality: 'state'
action_repeat: 1
discount: 0.99
episode_length: 200/${action_repeat}
val_episode_length: 200/${action_repeat}
train_steps: 10000/${action_repeat}

# misc
determinism: True # Remark. True if need to reproduce the results
seed: 42
eval: True
eval_freq: 1000
eval_episodes: 1
render_eval: True # Remark. True if need to visualize evaluation and render in human mode
save_video: false
save_model: false

# planning
iterations: 6
num_samples: 512
num_elites: 64
mixture_coef: 0.05
min_std: 0.05
temperature: 0.5
momentum: 0.1

# learning
batch_size: 256
max_buffer_size: 1000000
horizon: 5
reward_coef: 0.5
value_coef: 0.1
consistency_coef: 2
rho: 0.5
kappa: 0.1
lr: 1e-3
std_schedule: linear(0.5, ${min_std}, 4000)
horizon_schedule: linear(1, ${horizon}, 4000)
per_alpha: 0.6
per_beta: 0.4
grad_clip_norm: 10
seed_steps: 200
update_freq: 1
tau: 0.01
rew_beta: 5e-3

# architecture
enc_dim: 256
mlp_dim: 256
latent_dim: 50

# wandb (insert your own)
use_wandb: false
wandb_project: none
wandb_entity: none

